//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PSIA.Common.Soap.Objects.Model;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PSIA.CSEC
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class PermissionDictionaryDescriptor
    {

        private string dictionaryNameField;

        private CSECSymbolicPermission1 symbolicPermissionField;

        private bool symbolicPermissionFieldSpecified;

        private string permissionMaskField;

        private uint permissionBitOffsetField;

        private bool permissionBitOffsetFieldSpecified;

        /// <remarks/>
        public string dictionaryName
        {
            get
            {
                return this.dictionaryNameField;
            }
            set
            {
                this.dictionaryNameField = value;
            }
        }

        /// <remarks/>
        public CSECSymbolicPermission1 SymbolicPermission
        {
            get
            {
                return this.symbolicPermissionField;
            }
            set
            {
                this.symbolicPermissionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SymbolicPermissionSpecified
        {
            get
            {
                return this.symbolicPermissionFieldSpecified;
            }
            set
            {
                this.symbolicPermissionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string permissionMask
        {
            get
            {
                return this.permissionMaskField;
            }
            set
            {
                this.permissionMaskField = value;
            }
        }

        /// <remarks/>
        public uint permissionBitOffset
        {
            get
            {
                return this.permissionBitOffsetField;
            }
            set
            {
                this.permissionBitOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool permissionBitOffsetSpecified
        {
            get
            {
                return this.permissionBitOffsetFieldSpecified;
            }
            set
            {
                this.permissionBitOffsetFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum CSECSymbolicPermission1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/")]
        Item,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View")]
        View,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Statistics")]
        ViewStatistics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Logs")]
        ViewLogs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System")]
        ViewSystem,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/NetworkSettings")]
        ViewSystemNetworkSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/IOSettings")]
        ViewSystemIOSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/StorageSettings")]
        ViewSystemStorageSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/SerialPortSettings")]
        ViewSystemSerialPortSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/Diagnostics")]
        ViewSystemDiagnostics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/System/TimeSettings")]
        ViewSystemTimeSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/VideoDevice")]
        ViewVideoDevice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/VideoDevice/ImageSettings")]
        ViewVideoDeviceImageSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/VideoDevice/Overlays")]
        ViewVideoDeviceOverlays,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/VideoDevice/PrivacyMasks")]
        ViewVideoDevicePrivacyMasks,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/VideoDevice/OtherSettings")]
        ViewVideoDeviceOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/AudioDevice")]
        ViewAudioDevice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/AudioDevice/Microphone")]
        ViewAudioDeviceMicrophone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/AudioDevice/OtherSettings")]
        ViewAudioDeviceOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Codec")]
        ViewCodec,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Codec/Video")]
        ViewCodecVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Codec/Audio")]
        ViewCodecAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Codec/Other")]
        ViewCodecOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/PTZ")]
        ViewPTZ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/PTZ/PersistentPresets")]
        ViewPTZPersistentPresets,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/PTZ/TemporaryPresets")]
        ViewPTZTemporaryPresets,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/PTZ/OtherSettings")]
        ViewPTZOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Analytics")]
        ViewAnalytics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Analytics/Media")]
        ViewAnalyticsMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Analytics/Media/Video")]
        ViewAnalyticsMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Analytics/Media/Audio")]
        ViewAnalyticsMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Analytics/Media/Other")]
        ViewAnalyticsMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Event")]
        ViewEvent,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Event/Schedules")]
        ViewEventSchedules,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Event/Triggers")]
        ViewEventTriggers,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Event/Notifications")]
        ViewEventNotifications,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/AreaControl")]
        ViewAreaControl,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/AreaControl/Database")]
        ViewAreaControlDatabase,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/DeviceSettings")]
        ConfigureAreaControlDeviceSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/Zone")]
        ConfigureAreaControlZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Fire")]
        ViewFire,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Fire/FireDeviceSettings")]
        ViewFireFireDeviceSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Fire/Zone")]
        ViewFireZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Intrusion")]
        ViewIntrusion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Intrusion/DeviceSettings")]
        ViewIntrusionDeviceSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Intrusion/Zone")]
        ViewIntrusionZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security")]
        ViewSecurity,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/AddUser")]
        ViewSecurityAddUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/EditUser")]
        ViewSecurityEditUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/RemoveUser")]
        ViewSecurityRemoveUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/AddPermissionGroup")]
        ViewSecurityAddPermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/EditPermissionGroup")]
        ViewSecurityEditPermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Security/RemovePermissionGroup")]
        ViewSecurityRemovePermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording")]
        ViewRecording,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Media")]
        ViewRecordingMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Media/Video")]
        ViewRecordingMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Media/Audio")]
        ViewRecordingMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Media/Other")]
        ViewRecordingMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Metadata")]
        ViewRecordingMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Metadata/Analyticdata")]
        ViewRecordingMetadataAnalyticdata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/View/Recording/Metadata/Annotation")]
        ViewRecordingMetadataAnnotation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream")]
        Stream,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live")]
        StreamLive,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Media")]
        StreamLiveMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Media/Video")]
        StreamLiveMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Media/Audio")]
        StreamLiveMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Media/Other")]
        StreamLiveMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Metadata")]
        StreamLiveMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Live/Metadata/Analyticdata")]
        StreamLiveMetadataAnalyticdata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded")]
        StreamRecorded,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Media")]
        StreamRecordedMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Media/Video")]
        StreamRecordedMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Media/Audio")]
        StreamRecordedMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Media/Other")]
        StreamRecordedMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Metadata")]
        StreamRecordedMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Stream/Recorded/Metadata/Analyticdata")]
        StreamRecordedMetadataAnalyticdata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure")]
        Configure,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System")]
        ConfigureSystem,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/NetworkSettings")]
        ConfigureSystemNetworkSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/IOSettings")]
        ConfigureSystemIOSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/IOSettings/Inputs")]
        ConfigureSystemIOSettingsInputs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/IOSettings/Outputs")]
        ConfigureSystemIOSettingsOutputs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/StorageSettings")]
        ConfigureSystemStorageSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/SerialPortSettings")]
        ConfigureSystemSerialPortSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/Diagnostics")]
        ConfigureSystemDiagnostics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/System/TimeSettings")]
        ConfigureSystemTimeSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/VideoDevice")]
        ConfigureVideoDevice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/VideoDevice/ImageSettings")]
        ConfigureVideoDeviceImageSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/VideoDevice/Overlays")]
        ConfigureVideoDeviceOverlays,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/VideoDevice/PrivacyMasks")]
        ConfigureVideoDevicePrivacyMasks,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/VideoDevice/OtherSettings")]
        ConfigureVideoDeviceOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AudioDevice")]
        ConfigureAudioDevice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AudioDevice/Microphone")]
        ConfigureAudioDeviceMicrophone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AudioDevice/OtherSettings")]
        ConfigureAudioDeviceOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Codec")]
        ConfigureCodec,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Codec/Video")]
        ConfigureCodecVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Codec/Audio")]
        ConfigureCodecAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Codec/Other")]
        ConfigureCodecOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/PTZ")]
        ConfigurePTZ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/PTZ/PersistentPresets")]
        ConfigurePTZPersistentPresets,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/PTZ/TemporaryPresets")]
        ConfigurePTZTemporaryPresets,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/PTZ/OtherSettings")]
        ConfigurePTZOtherSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Analytics")]
        ConfigureAnalytics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Analytics/Media")]
        ConfigureAnalyticsMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Analytics/Media/Video")]
        ConfigureAnalyticsMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Analytics/Media/Audio")]
        ConfigureAnalyticsMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Analytics/Media/Other")]
        ConfigureAnalyticsMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Event")]
        ConfigureEvent,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Event/Schedules")]
        ConfigureEventSchedules,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Event/Triggers")]
        ConfigureEventTriggers,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Event/Notifications")]
        ConfigureEventNotifications,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl")]
        ConfigureAreaControl,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/Database")]
        ConfigureAreaControlDatabase,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/DeviceSettings")]
        ConfigureAreaControlDeviceSettings1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/Partition")]
        ConfigureAreaControlPartition,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/AreaControl/Zone")]
        ConfigureAreaControlZone1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Fire")]
        ConfigureFire,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Fire/FireDeviceSettings")]
        ConfigureFireFireDeviceSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Fire/Partition")]
        ConfigureFirePartition,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Fire/Zone")]
        ConfigureFireZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Intrusion")]
        ConfigureIntrusion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Intrusion/DeviceSettings")]
        ConfigureIntrusionDeviceSettings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Intrusion/Partition")]
        ConfigureIntrusionPartition,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Intrusion/Zone")]
        ConfigureIntrusionZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security")]
        ConfigureSecurity,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/AddUser")]
        ConfigureSecurityAddUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/EditUser")]
        ConfigureSecurityEditUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/RemoveUser")]
        ConfigureSecurityRemoveUser,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/AddPermissionGroup")]
        ConfigureSecurityAddPermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/EditPermissionGroup")]
        ConfigureSecurityEditPermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Security/RemovePermissionGroup")]
        ConfigureSecurityRemovePermissionGroup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording")]
        ConfigureRecording,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Media")]
        ConfigureRecordingMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Media/Video")]
        ConfigureRecordingMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Media/Audio")]
        ConfigureRecordingMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Media/Other")]
        ConfigureRecordingMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Metadata")]
        ConfigureRecordingMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Metadata/Analyticdata")]
        ConfigureRecordingMetadataAnalyticdata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Configure/Recording/Metadata/Annotation")]
        ConfigureRecordingMetadataAnnotation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import")]
        Import,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/Configuration")]
        ImportConfiguration,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/Software")]
        ImportSoftware,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/Firmware")]
        ImportFirmware,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/HardwareLogic")]
        ImportHardwareLogic,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/Database")]
        ImportDatabase,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Import/Credentials")]
        ImportCredentials,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control")]
        Control,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/System")]
        ControlSystem,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/System/Restart")]
        ControlSystemRestart,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/System/Reboot")]
        ControlSystemReboot,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/System/FactoryReset")]
        ControlSystemFactoryReset,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/PTZ")]
        ControlPTZ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/PTZ/PanTilt")]
        ControlPTZPanTilt,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/PTZ/Zoom")]
        ControlPTZZoom,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/PTZ/GotoPreset")]
        ControlPTZGotoPreset,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/AreaControl")]
        ControlAreaControl,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/AreaControl/ArmZone")]
        ControlAreaControlArmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/AreaControl/DisarmZone")]
        ControlAreaControlDisarmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Fire")]
        ControlFire,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Fire/ArmZone")]
        ControlFireArmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Fire/DisarmZone")]
        ControlFireDisarmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Intrusion")]
        ControlIntrusion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Intrusion/ArmZone")]
        ControlIntrusionArmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Intrusion/DisarmZone")]
        ControlIntrusionDisarmZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Control/Intrusion/BypassZone")]
        ControlIntrusionBypassZone,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search")]
        Search,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Media")]
        SearchMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Media/Video")]
        SearchMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Media/Audio")]
        SearchMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Media/Other")]
        SearchMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata")]
        SearchMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata/Analytics")]
        SearchMetadataAnalytics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata/Analytics/Video")]
        SearchMetadataAnalyticsVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata/Analytics/Audio")]
        SearchMetadataAnalyticsAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata/Analytics/Other")]
        SearchMetadataAnalyticsOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Search/Metadata/Other")]
        SearchMetadataOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export")]
        Export,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Configuration")]
        ExportConfiguration,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Software")]
        ExportSoftware,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Firmware")]
        ExportFirmware,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/HardwareLogic")]
        ExportHardwareLogic,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Database")]
        ExportDatabase,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Credentials")]
        ExportCredentials,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Logs")]
        ExportLogs,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Statistics")]
        ExportStatistics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Media")]
        ExportMedia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Media/Video")]
        ExportMediaVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Media/Audio")]
        ExportMediaAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Media/Other")]
        ExportMediaOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata")]
        ExportMetadata,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata/Analytics")]
        ExportMetadataAnalytics,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata/Analytics/Video")]
        ExportMetadataAnalyticsVideo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata/Analytics/Audio")]
        ExportMetadataAnalyticsAudio,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata/Analytics/Other")]
        ExportMetadataAnalyticsOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Export/Metadata/Other")]
        ExportMetadataOther,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/Auditer")]
        Auditer,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/ResetDeviceOwnership")]
        ResetDeviceOwnership,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class CommonTypeCustomExtension
    {

        private string customExtensionNameField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string CustomExtensionName
        {
            get
            {
                return this.customExtensionNameField;
            }
            set
            {
                this.customExtensionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

   

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class PrivilegeElement
    {

        private ReferenceID[] timeScheduleIDListField;

        private uint authorityLevelField;

        private bool authorityLevelFieldSpecified;

        private ReferenceID[] partitionIDListField;

        private ReferenceID[] portalIDListField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TimeScheduleID", IsNullable = false)]
        public ReferenceID[] TimeScheduleIDList
        {
            get
            {
                return this.timeScheduleIDListField;
            }
            set
            {
                this.timeScheduleIDListField = value;
            }
        }

        /// <remarks/>
        public uint AuthorityLevel
        {
            get
            {
                return this.authorityLevelField;
            }
            set
            {
                this.authorityLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthorityLevelSpecified
        {
            get
            {
                return this.authorityLevelFieldSpecified;
            }
            set
            {
                this.authorityLevelFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PartitionID", IsNullable = false)]
        public ReferenceID[] PartitionIDList
        {
            get
            {
                return this.partitionIDListField;
            }
            set
            {
                this.partitionIDListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PortalID", IsNullable = false)]
        public ReferenceID[] PortalIDList
        {
            get
            {
                return this.portalIDListField;
            }
            set
            {
                this.portalIDListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class Privilege
    {

        private PrivilegeElement allowField;

        private PrivilegeElement restrictField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public PrivilegeElement Allow
        {
            get
            {
                return this.allowField;
            }
            set
            {
                this.allowField = value;
            }
        }

        /// <remarks/>
        public PrivilegeElement Restrict
        {
            get
            {
                return this.restrictField;
            }
            set
            {
                this.restrictField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

  

   

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class ExplicitPermissionDescriptor
    {

        private string resourcePathField;

        private ResourceAction[] allowedActionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string ResourcePath
        {
            get
            {
                return this.resourcePathField;
            }
            set
            {
                this.resourcePathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowedAction")]
        public ResourceAction[] AllowedAction
        {
            get
            {
                return this.allowedActionField;
            }
            set
            {
                this.allowedActionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum ResourceAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Read,

        /// <remarks/>
        Update,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Index,

        /// <remarks/>
        Export,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class SymbolicPermissionDescriptor
    {

        private PermissionDictionaryDescriptor permissionDictionaryDescriptorField;

        /// <remarks/>
        public PermissionDictionaryDescriptor PermissionDictionaryDescriptor
        {
            get
            {
                return this.permissionDictionaryDescriptorField;
            }
            set
            {
                this.permissionDictionaryDescriptorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class UserCODE
    {

        private uint idField;

        private string cODEField;

        private CODEClass cODEClassField;

        private CSECCustomExtension[] userCODECustomExtensionField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }

        /// <remarks/>
        public CODEClass CODEClass
        {
            get
            {
                return this.cODEClassField;
            }
            set
            {
                this.cODEClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserCODECustomExtension")]
        public CSECCustomExtension[] UserCODECustomExtension
        {
            get
            {
                return this.userCODECustomExtensionField;
            }
            set
            {
                this.userCODECustomExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum CODEClass
    {

        /// <remarks/>
        INTRUSION,

        /// <remarks/>
        ACCESS,

        /// <remarks/>
        FIRE,

        /// <remarks/>
        CUSTOM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECCustomExtension
    {

        private string customExtensionNameField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string CustomExtensionName
        {
            get
            {
                return this.customExtensionNameField;
            }
            set
            {
                this.customExtensionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class UserLogin
    {

        private string usernameField;

        private string passwordField;

        private CSECCustomExtension[] userLoginCustomExtensionField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserLoginCustomExtension")]
        public CSECCustomExtension[] UserLoginCustomExtension
        {
            get
            {
                return this.userLoginCustomExtensionField;
            }
            set
            {
                this.userLoginCustomExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CertificateAuthorityList
    {

        private CertificateAuthority[] certificateAuthorityField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CertificateAuthority")]
        public CertificateAuthority[] CertificateAuthority
        {
            get
            {
                return this.certificateAuthorityField;
            }
            set
            {
                this.certificateAuthorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CertificateAuthority
    {

        private uint idField;

        private RDN[] distinguishedNameField;

        private string[] crlDistributionPointField;

        private string[] ocspInfoAccessField;

        private string versionField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RDN[] DistinguishedName
        {
            get
            {
                return this.distinguishedNameField;
            }
            set
            {
                this.distinguishedNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("crlDistributionPoint", DataType = "anyURI")]
        public string[] crlDistributionPoint
        {
            get
            {
                return this.crlDistributionPointField;
            }
            set
            {
                this.crlDistributionPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ocspInfoAccess", DataType = "anyURI")]
        public string[] ocspInfoAccess
        {
            get
            {
                return this.ocspInfoAccessField;
            }
            set
            {
                this.ocspInfoAccessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class RDN
    {

        private RDNLongLabel rDNLongLabelField;

        private RDNShortLabel rDNShortLabelField;

        private bool rDNShortLabelFieldSpecified;

        private string rDNValueField;

        /// <remarks/>
        public RDNLongLabel RDNLongLabel
        {
            get
            {
                return this.rDNLongLabelField;
            }
            set
            {
                this.rDNLongLabelField = value;
            }
        }

        /// <remarks/>
        public RDNShortLabel RDNShortLabel
        {
            get
            {
                return this.rDNShortLabelField;
            }
            set
            {
                this.rDNShortLabelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RDNShortLabelSpecified
        {
            get
            {
                return this.rDNShortLabelFieldSpecified;
            }
            set
            {
                this.rDNShortLabelFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RDNValue
        {
            get
            {
                return this.rDNValueField;
            }
            set
            {
                this.rDNValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum RDNLongLabel
    {

        /// <remarks/>
        CountryName,

        /// <remarks/>
        StateOrProvinceName,

        /// <remarks/>
        LocalityName,

        /// <remarks/>
        OrganizationName,

        /// <remarks/>
        OrganizationalUnitName,

        /// <remarks/>
        CommonName,

        /// <remarks/>
        GivenName,

        /// <remarks/>
        SurName,

        /// <remarks/>
        TitleName,

        /// <remarks/>
        UnrestrictedName,

        /// <remarks/>
        Initials,

        /// <remarks/>
        StreetAddress,

        /// <remarks/>
        EmailAddress,

        /// <remarks/>
        DomainComponent,

        /// <remarks/>
        GeneralQualifier,

        /// <remarks/>
        DNQualifier,

        /// <remarks/>
        UserId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum RDNShortLabel
    {

        /// <remarks/>
        C,

        /// <remarks/>
        ST,

        /// <remarks/>
        L,

        /// <remarks/>
        O,

        /// <remarks/>
        OU,

        /// <remarks/>
        CN,

        /// <remarks/>
        GN,

        /// <remarks/>
        SN,

        /// <remarks/>
        T,

        /// <remarks/>
        N,

        /// <remarks/>
        I,

        /// <remarks/>
        STREET,

        /// <remarks/>
        EA,

        /// <remarks/>
        DC,

        /// <remarks/>
        GENQ,

        /// <remarks/>
        DNQ,

        /// <remarks/>
        UserId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECUserList
    {

        private CSECUser[] cSECUserField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CSECUser")]
        public CSECUser[] CSECUser
        {
            get
            {
                return this.cSECUserField;
            }
            set
            {
                this.cSECUserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECUser
    {

        private uint idField;

        private bool userEnabledField;

        private string userDescriptionField;

        private string fullNameField;

        private string userGUIDField;

        private UserLogin userLoginField;

        private UserCODE[] userCODEListField;

        private uint[] userPermissionGroupIdField;

        private CSECCustomExtension[] userCustomExtensionField;

        private string versionField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public bool userEnabled
        {
            get
            {
                return this.userEnabledField;
            }
            set
            {
                this.userEnabledField = value;
            }
        }

        /// <remarks/>
        public string userDescription
        {
            get
            {
                return this.userDescriptionField;
            }
            set
            {
                this.userDescriptionField = value;
            }
        }

        /// <remarks/>
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        public string userGUID
        {
            get
            {
                return this.userGUIDField;
            }
            set
            {
                this.userGUIDField = value;
            }
        }

        /// <remarks/>
        public UserLogin UserLogin
        {
            get
            {
                return this.userLoginField;
            }
            set
            {
                this.userLoginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public UserCODE[] UserCODEList
        {
            get
            {
                return this.userCODEListField;
            }
            set
            {
                this.userCODEListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserPermissionGroupId")]
        public uint[] UserPermissionGroupId
        {
            get
            {
                return this.userPermissionGroupIdField;
            }
            set
            {
                this.userPermissionGroupIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserCustomExtension")]
        public CSECCustomExtension[] UserCustomExtension
        {
            get
            {
                return this.userCustomExtensionField;
            }
            set
            {
                this.userCustomExtensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class DistinguishedName
    {

        private RDN[] rDNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RDN")]
        public RDN[] RDN
        {
            get
            {
                return this.rDNField;
            }
            set
            {
                this.rDNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECOwnershipCookie
    {

        private string ownerCodeField;

        private string expiresField;

        private string pathField;

        private string cookieVersionField;

        private string issuerSignatureField;

        private string versionField;

        /// <remarks/>
        public string ownerCode
        {
            get
            {
                return this.ownerCodeField;
            }
            set
            {
                this.ownerCodeField = value;
            }
        }

        /// <remarks/>
        public string expires
        {
            get
            {
                return this.expiresField;
            }
            set
            {
                this.expiresField = value;
            }
        }

        /// <remarks/>
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public string cookieVersion
        {
            get
            {
                return this.cookieVersionField;
            }
            set
            {
                this.cookieVersionField = value;
            }
        }

        /// <remarks/>
        public string issuerSignature
        {
            get
            {
                return this.issuerSignatureField;
            }
            set
            {
                this.issuerSignatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECOwnershipScope
    {

        private PermissionDescriptorList permissionDescriptorListField;

        private string versionField;

        /// <remarks/>
        public PermissionDescriptorList PermissionDescriptorList
        {
            get
            {
                return this.permissionDescriptorListField;
            }
            set
            {
                this.permissionDescriptorListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class PermissionDescriptorList
    {

        private PermissionDescriptor[] permissionDescriptorField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PermissionDescriptor")]
        public PermissionDescriptor[] PermissionDescriptor
        {
            get
            {
                return this.permissionDescriptorField;
            }
            set
            {
                this.permissionDescriptorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class PermissionDescriptor
    {

        private uint idField;

        private object itemField;

        private string loginPortAffinityField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExplicitPermissionDescriptor", typeof(ExplicitPermissionDescriptor))]
        [System.Xml.Serialization.XmlElementAttribute("SymbolicPermissionDescriptor", typeof(SymbolicPermissionDescriptor))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string loginPortAffinity
        {
            get
            {
                return this.loginPortAffinityField;
            }
            set
            {
                this.loginPortAffinityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECOwnershipStatus
    {

        private bool ownedField;

        private string ownerGUIDField;

        private string versionField;

        /// <remarks/>
        public bool owned
        {
            get
            {
                return this.ownedField;
            }
            set
            {
                this.ownedField = value;
            }
        }

        /// <remarks/>
        public string ownerGUID
        {
            get
            {
                return this.ownerGUIDField;
            }
            set
            {
                this.ownerGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECPermissionGroupList
    {

        private CSECPermissionGroup[] cSECPermissionGroupField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CSECPermissionGroup")]
        public CSECPermissionGroup[] CSECPermissionGroup
        {
            get
            {
                return this.cSECPermissionGroupField;
            }
            set
            {
                this.cSECPermissionGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECPermissionGroup
    {

        private uint idField;

        private string groupGUIDField;

        private bool groupEnabledField;

        private string groupDescriptionField;

        private PermissionDescriptorList permissionDescriptorListField;

        private DeviceScopeRestriction[] deviceScopeRestrictionListField;

        private CSECCustomExtension[] permissionGroupCustomExtensionField;

        private string versionField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string groupGUID
        {
            get
            {
                return this.groupGUIDField;
            }
            set
            {
                this.groupGUIDField = value;
            }
        }

        /// <remarks/>
        public bool groupEnabled
        {
            get
            {
                return this.groupEnabledField;
            }
            set
            {
                this.groupEnabledField = value;
            }
        }

        /// <remarks/>
        public string groupDescription
        {
            get
            {
                return this.groupDescriptionField;
            }
            set
            {
                this.groupDescriptionField = value;
            }
        }

        /// <remarks/>
        public PermissionDescriptorList PermissionDescriptorList
        {
            get
            {
                return this.permissionDescriptorListField;
            }
            set
            {
                this.permissionDescriptorListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DeviceScopeRestriction[] DeviceScopeRestrictionList
        {
            get
            {
                return this.deviceScopeRestrictionListField;
            }
            set
            {
                this.deviceScopeRestrictionListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PermissionGroupCustomExtension")]
        public CSECCustomExtension[] PermissionGroupCustomExtension
        {
            get
            {
                return this.permissionGroupCustomExtensionField;
            }
            set
            {
                this.permissionGroupCustomExtensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class DeviceScopeRestriction
    {

        private uint idField;

        private string restrictionDescriptionField;

        private ScopeRestrictionType typeField;

        private string deviceGUIDField;

        private string[] subDeviceResourceRestrictionField;

        private string[] subDevVideoInPortRestrictionField;

        private string[] subDevAudioInPortRestrictionField;

        private string[] subDevIOPortRestrictionField;

        private string[] subDevSerialPortRestrictionField;

        private string[] subDevStreamChannelRestrictionField;

        private PermissionInfoList aCWGPermissionInfoListField;

        private CSECCustomExtension[] deviceScopeRestrictionCustomExtensionField;

        /// <remarks/>
        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string restrictionDescription
        {
            get
            {
                return this.restrictionDescriptionField;
            }
            set
            {
                this.restrictionDescriptionField = value;
            }
        }

        /// <remarks/>
        public ScopeRestrictionType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string deviceGUID
        {
            get
            {
                return this.deviceGUIDField;
            }
            set
            {
                this.deviceGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDeviceResourceRestriction", DataType = "anyURI")]
        public string[] subDeviceResourceRestriction
        {
            get
            {
                return this.subDeviceResourceRestrictionField;
            }
            set
            {
                this.subDeviceResourceRestrictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDevVideoInPortRestriction")]
        public string[] subDevVideoInPortRestriction
        {
            get
            {
                return this.subDevVideoInPortRestrictionField;
            }
            set
            {
                this.subDevVideoInPortRestrictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDevAudioInPortRestriction")]
        public string[] subDevAudioInPortRestriction
        {
            get
            {
                return this.subDevAudioInPortRestrictionField;
            }
            set
            {
                this.subDevAudioInPortRestrictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDevIOPortRestriction")]
        public string[] subDevIOPortRestriction
        {
            get
            {
                return this.subDevIOPortRestrictionField;
            }
            set
            {
                this.subDevIOPortRestrictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDevSerialPortRestriction")]
        public string[] subDevSerialPortRestriction
        {
            get
            {
                return this.subDevSerialPortRestrictionField;
            }
            set
            {
                this.subDevSerialPortRestrictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subDevStreamChannelRestriction")]
        public string[] subDevStreamChannelRestriction
        {
            get
            {
                return this.subDevStreamChannelRestrictionField;
            }
            set
            {
                this.subDevStreamChannelRestrictionField = value;
            }
        }

        /// <remarks/>
        public PermissionInfoList ACWGPermissionInfoList
        {
            get
            {
                return this.aCWGPermissionInfoListField;
            }
            set
            {
                this.aCWGPermissionInfoListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviceScopeRestrictionCustomExtension")]
        public CSECCustomExtension[] DeviceScopeRestrictionCustomExtension
        {
            get
            {
                return this.deviceScopeRestrictionCustomExtensionField;
            }
            set
            {
                this.deviceScopeRestrictionCustomExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum ScopeRestrictionType
    {

        /// <remarks/>
        Local,

        /// <remarks/>
        Global,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class DeviceScopeRestrictionList
    {

        private DeviceScopeRestriction[] deviceScopeRestrictionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviceScopeRestriction")]
        public DeviceScopeRestriction[] DeviceScopeRestriction
        {
            get
            {
                return this.deviceScopeRestrictionField;
            }
            set
            {
                this.deviceScopeRestrictionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class NegotiatedMKIList
    {

        private NegotiatedMKI[] negotiatedMKIField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NegotiatedMKI")]
        public NegotiatedMKI[] NegotiatedMKI
        {
            get
            {
                return this.negotiatedMKIField;
            }
            set
            {
                this.negotiatedMKIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class NegotiatedMKI
    {

        private uint mKIField;

        private string versionField;

        /// <remarks/>
        public uint MKI
        {
            get
            {
                return this.mKIField;
            }
            set
            {
                this.mKIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MKIKeyList
    {

        private MKIKey[] mKIKeyField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MKIKey")]
        public MKIKey[] MKIKey
        {
            get
            {
                return this.mKIKeyField;
            }
            set
            {
                this.mKIKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MKIKey
    {

        private uint mKIField;

        private CSECMediaContext mKIMediaContextField;

        private string masterKeyField;

        private string masterSaltField;

        private string cipherField;

        private string srtpKeyDerivationRateField;

        private string srtpKeyLifetimeField;

        private string srtcpKeyDerivationRateField;

        private string srtcpKeyLifetimeField;

        private string keyRotationPreferenceMKIField;

        private string versionField;

        /// <remarks/>
        public uint MKI
        {
            get
            {
                return this.mKIField;
            }
            set
            {
                this.mKIField = value;
            }
        }

        /// <remarks/>
        public CSECMediaContext MKIMediaContext
        {
            get
            {
                return this.mKIMediaContextField;
            }
            set
            {
                this.mKIMediaContextField = value;
            }
        }

        /// <remarks/>
        public string masterKey
        {
            get
            {
                return this.masterKeyField;
            }
            set
            {
                this.masterKeyField = value;
            }
        }

        /// <remarks/>
        public string masterSalt
        {
            get
            {
                return this.masterSaltField;
            }
            set
            {
                this.masterSaltField = value;
            }
        }

        /// <remarks/>
        public string Cipher
        {
            get
            {
                return this.cipherField;
            }
            set
            {
                this.cipherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string srtpKeyDerivationRate
        {
            get
            {
                return this.srtpKeyDerivationRateField;
            }
            set
            {
                this.srtpKeyDerivationRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string srtpKeyLifetime
        {
            get
            {
                return this.srtpKeyLifetimeField;
            }
            set
            {
                this.srtpKeyLifetimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string srtcpKeyDerivationRate
        {
            get
            {
                return this.srtcpKeyDerivationRateField;
            }
            set
            {
                this.srtcpKeyDerivationRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string srtcpKeyLifetime
        {
            get
            {
                return this.srtcpKeyLifetimeField;
            }
            set
            {
                this.srtcpKeyLifetimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string keyRotationPreferenceMKI
        {
            get
            {
                return this.keyRotationPreferenceMKIField;
            }
            set
            {
                this.keyRotationPreferenceMKIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class CSECMediaContext
    {

        private string streamingChannelIDField;

        private ContentType streamingMediaTypeField;

        private bool streamingMediaTypeFieldSpecified;

        private string rtspSessionIDField;

        private string ssrcIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string StreamingChannelID
        {
            get
            {
                return this.streamingChannelIDField;
            }
            set
            {
                this.streamingChannelIDField = value;
            }
        }

        /// <remarks/>
        public ContentType StreamingMediaType
        {
            get
            {
                return this.streamingMediaTypeField;
            }
            set
            {
                this.streamingMediaTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreamingMediaTypeSpecified
        {
            get
            {
                return this.streamingMediaTypeFieldSpecified;
            }
            set
            {
                this.streamingMediaTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string rtspSessionID
        {
            get
            {
                return this.rtspSessionIDField;
            }
            set
            {
                this.rtspSessionIDField = value;
            }
        }

        /// <remarks/>
        public string ssrcID
        {
            get
            {
                return this.ssrcIDField;
            }
            set
            {
                this.ssrcIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum ContentType
    {

        /// <remarks/>
        video,

        /// <remarks/>
        audio,

        /// <remarks/>
        metadata,

        /// <remarks/>
        text,

        /// <remarks/>
        mixed,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MIKEYProperties
    {

        private MIKEYExchangeMethod[] mIKEYExchangeMethodField;

        private MIKEYTransport[] mIKEYTransportField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MIKEYExchangeMethod")]
        public MIKEYExchangeMethod[] MIKEYExchangeMethod
        {
            get
            {
                return this.mIKEYExchangeMethodField;
            }
            set
            {
                this.mIKEYExchangeMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MIKEYTransport")]
        public MIKEYTransport[] MIKEYTransport
        {
            get
            {
                return this.mIKEYTransportField;
            }
            set
            {
                this.mIKEYTransportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum MIKEYExchangeMethod
    {

        /// <remarks/>
        PSK,

        /// <remarks/>
        PKE,

        /// <remarks/>
        DH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DH-HMAC")]
        DHHMAC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RSA-R")]
        RSAR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum MIKEYTransport
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PSIA-REST-TUNNEL")]
        PSIARESTTUNNEL,

        /// <remarks/>
        RTSP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SIP-SDP")]
        SIPSDP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MIKEYMessage
    {

        private CSECMediaContext mIKEYMediaContextField;

        private string messageField;

        private string versionField;

        /// <remarks/>
        public CSECMediaContext MIKEYMediaContext
        {
            get
            {
                return this.mIKEYMediaContextField;
            }
            set
            {
                this.mIKEYMediaContextField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
}