//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PSIA.Common.Soap.Objects
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MetaSessionSupport
    {

        private MetaFormat[] metaFormatsField;

        private SessionType[] metaSessionTypesField;

        private bool multicastCapableField;

        private bool scheduleCapableField;

        private bool queryParmsSupportedField;

        private bool queryParmsSupportedFieldSpecified;

        private bool receivesMetadataField;

        private bool receivesMetadataFieldSpecified;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("metaFormat", IsNullable = false)]
        public MetaFormat[] metaFormats
        {
            get
            {
                return this.metaFormatsField;
            }
            set
            {
                this.metaFormatsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("metaSessionType", IsNullable = false)]
        public SessionType[] metaSessionTypes
        {
            get
            {
                return this.metaSessionTypesField;
            }
            set
            {
                this.metaSessionTypesField = value;
            }
        }

        /// <remarks/>
        public bool multicastCapable
        {
            get
            {
                return this.multicastCapableField;
            }
            set
            {
                this.multicastCapableField = value;
            }
        }

        /// <remarks/>
        public bool scheduleCapable
        {
            get
            {
                return this.scheduleCapableField;
            }
            set
            {
                this.scheduleCapableField = value;
            }
        }

        /// <remarks/>
        public bool queryParmsSupported
        {
            get
            {
                return this.queryParmsSupportedField;
            }
            set
            {
                this.queryParmsSupportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queryParmsSupportedSpecified
        {
            get
            {
                return this.queryParmsSupportedFieldSpecified;
            }
            set
            {
                this.queryParmsSupportedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool receivesMetadata
        {
            get
            {
                return this.receivesMetadataField;
            }
            set
            {
                this.receivesMetadataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receivesMetadataSpecified
        {
            get
            {
                return this.receivesMetadataFieldSpecified;
            }
            set
            {
                this.receivesMetadataFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum MetaFormat
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("gmch-psia")]
        gmchpsia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xml-psia")]
        xmlpsia,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class SessionType
    {

        private SessionProtocolType metaSessionProtocolField;

        private SessionFlowType metaSessionFlowTypeField;

        private bool metaSessionFlowTypeFieldSpecified;

        private bool metaSessionPersistentField;

        private bool metaSessionPersistentFieldSpecified;

        /// <remarks/>
        public SessionProtocolType metaSessionProtocol
        {
            get
            {
                return this.metaSessionProtocolField;
            }
            set
            {
                this.metaSessionProtocolField = value;
            }
        }

        /// <remarks/>
        public SessionFlowType metaSessionFlowType
        {
            get
            {
                return this.metaSessionFlowTypeField;
            }
            set
            {
                this.metaSessionFlowTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metaSessionFlowTypeSpecified
        {
            get
            {
                return this.metaSessionFlowTypeFieldSpecified;
            }
            set
            {
                this.metaSessionFlowTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool metaSessionPersistent
        {
            get
            {
                return this.metaSessionPersistentField;
            }
            set
            {
                this.metaSessionPersistentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metaSessionPersistentSpecified
        {
            get
            {
                return this.metaSessionPersistentFieldSpecified;
            }
            set
            {
                this.metaSessionPersistentFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum SessionProtocolType
    {

        /// <remarks/>
        RESTSyncSessionTargetSend,

        /// <remarks/>
        RESTAsyncSessionBackSourceSend,

        /// <remarks/>
        RESTRTPStreamSrcOutUDP,

        /// <remarks/>
        RESTRTPStreamSrcOutTCP,

        /// <remarks/>
        RTSPRTPStreamSrcOut,

        /// <remarks/>
        RTSPRTPStreamSrcOutInterleaved,

        /// <remarks/>
        RESTAsyncSessionBackForReceive,

        /// <remarks/>
        RESTRTPStreamInUDP,

        /// <remarks/>
        RESTRTPStreamInTCP,

        /// <remarks/>
        EmailNotification,

        /// <remarks/>
        RESTSessionSrcOutRawTCP,

        /// <remarks/>
        RESTSessionIntoSrcRawTCP,

        /// <remarks/>
        RESTStreamSrcOutRawUDP,

        /// <remarks/>
        RESTRTPAsyncStreamSrcOutUDP,

        /// <remarks/>
        RESTAsyncSessionSrcOutRawTCP,

        /// <remarks/>
        RESTAsyncSessionSrcOutRawUDP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum SessionFlowType
    {

        /// <remarks/>
        datastream,

        /// <remarks/>
        transaction,

        /// <remarks/>
        streamOrTransaction,

        /// <remarks/>
        stateful,

        /// <remarks/>
        streamAndOrStateful,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class MetadataFilterSpec
    {

        private string[][] metadataNameListField;

        private uint[][] metadataXChannelListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("metadataIDString", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI", IsNullable = false)]
        public string[][] metadataNameList
        {
            get
            {
                return this.metadataNameListField;
            }
            set
            {
                this.metadataNameListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("metaChannel", typeof(uint), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public uint[][] metadataXChannelList
        {
            get
            {
                return this.metadataXChannelListField;
            }
            set
            {
                this.metadataXChannelListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class MetadataXChannelList
    {

        private string[] metaXChannelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metaXChannel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] metaXChannel
        {
            get
            {
                return this.metaXChannelField;
            }
            set
            {
                this.metaXChannelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class MetadataChannelList
    {

        private uint[] metaChannelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metaChannel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint[] metaChannel
        {
            get
            {
                return this.metaChannelField;
            }
            set
            {
                this.metaChannelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class MetadataNameList
    {

        private string[] metadataIDStringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadataIDString", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string[] metadataIDString
        {
            get
            {
                return this.metadataIDStringField;
            }
            set
            {
                this.metadataIDStringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class LoginCredentials
    {

        private string credentialTypeField;

        private string credentialDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string credentialType
        {
            get
            {
                return this.credentialTypeField;
            }
            set
            {
                this.credentialTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string credentialDefinition
        {
            get
            {
                return this.credentialDefinitionField;
            }
            set
            {
                this.credentialDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class LoginInfo
    {

        private string userNameField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class SessionLogin
    {

        private AuthenticationMode authModeField;

        private LoginInfo userLoginField;

        private LoginCredentials credentialObjectField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AuthenticationMode authMode
        {
            get
            {
                return this.authModeField;
            }
            set
            {
                this.authModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LoginInfo userLogin
        {
            get
            {
                return this.userLoginField;
            }
            set
            {
                this.userLoginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LoginCredentials credentialObject
        {
            get
            {
                return this.credentialObjectField;
            }
            set
            {
                this.credentialObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum AuthenticationMode
    {

        /// <remarks/>
        none,

        /// <remarks/>
        basic,

        /// <remarks/>
        digest,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https-SSLv3")]
        httpsSSLv3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https-TLSv1")]
        httpsTLSv1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https-TLSv1.1")]
        httpsTLSv11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https-TLSv1.2")]
        httpsTLSv12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https-TLSv1.x")]
        httpsTLSv1x,

        /// <remarks/>
        any,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class MetaXportParms
    {

        private uint metaSessionIDField;

        private MetaFormat metaFormatField;

        private SessionProtocolType metaSessionTypeField;

        private SessionFlowType metaSessionFlowTypeField;

        private SessionTargetRole metaSessionRoleField;

        private bool metaSessionRoleFieldSpecified;

        private SessionLogin metaSessionLoginField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private NetCastMode netcastModeField;

        private bool netcastModeFieldSpecified;

        private bool transactionAckField;

        private bool transactionAckFieldSpecified;

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private MetaSessionPersistence metaSessionPersistenceField;

        private bool metaSessionPersistenceFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint metaSessionID
        {
            get
            {
                return this.metaSessionIDField;
            }
            set
            {
                this.metaSessionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaFormat metaFormat
        {
            get
            {
                return this.metaFormatField;
            }
            set
            {
                this.metaFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionProtocolType metaSessionType
        {
            get
            {
                return this.metaSessionTypeField;
            }
            set
            {
                this.metaSessionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionFlowType metaSessionFlowType
        {
            get
            {
                return this.metaSessionFlowTypeField;
            }
            set
            {
                this.metaSessionFlowTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionTargetRole metaSessionRole
        {
            get
            {
                return this.metaSessionRoleField;
            }
            set
            {
                this.metaSessionRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metaSessionRoleSpecified
        {
            get
            {
                return this.metaSessionRoleFieldSpecified;
            }
            set
            {
                this.metaSessionRoleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionLogin metaSessionLogin
        {
            get
            {
                return this.metaSessionLoginField;
            }
            set
            {
                this.metaSessionLoginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetHostName", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("targetIPAddress", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("targetIPv6Address", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NetCastMode netcastMode
        {
            get
            {
                return this.netcastModeField;
            }
            set
            {
                this.netcastModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool netcastModeSpecified
        {
            get
            {
                return this.netcastModeFieldSpecified;
            }
            set
            {
                this.netcastModeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool transactionAck
        {
            get
            {
                return this.transactionAckField;
            }
            set
            {
                this.transactionAckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionAckSpecified
        {
            get
            {
                return this.transactionAckFieldSpecified;
            }
            set
            {
                this.transactionAckFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadataChannelList", typeof(MetadataChannelList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("metadataFilterRecord", typeof(MetadataFilterSpec), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("metadataNameList", typeof(MetadataNameList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("metadataXChannelList", typeof(MetadataXChannelList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaSessionPersistence metaSessionPersistence
        {
            get
            {
                return this.metaSessionPersistenceField;
            }
            set
            {
                this.metaSessionPersistenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metaSessionPersistenceSpecified
        {
            get
            {
                return this.metaSessionPersistenceFieldSpecified;
            }
            set
            {
                this.metaSessionPersistenceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum SessionTargetRole
    {

        /// <remarks/>
        primary,

        /// <remarks/>
        alternate,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":targetHostName")]
        targetHostName,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":targetIPAddress")]
        targetIPAddress,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":targetIPv6Address")]
        targetIPv6Address,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum NetCastMode
    {

        /// <remarks/>
        unicast,

        /// <remarks/>
        multicast,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":metadataChannelList")]
        metadataChannelList,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":metadataFilterRecord")]
        metadataFilterRecord,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":metadataNameList")]
        metadataNameList,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":metadataXChannelList")]
        metadataXChannelList,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum MetaSessionPersistence
    {

        /// <remarks/>
        dynamic,

        /// <remarks/>
        @static,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class MetaSessionParms
    {

        private MetaXportParms[] metaXportParmsField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metaXportParms", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetaXportParms[] metaXportParms
        {
            get
            {
                return this.metaXportParmsField;
            }
            set
            {
                this.metaXportParmsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
}