//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:psialliance-org")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:psialliance-org", IsNullable=false)]
public partial class MetaSessionSupport {
    
    private MetaFormat[] metaFormatsField;
    
    private SessionType[] metaSessionTypesField;
    
    private bool multicastCapableField;
    
    private bool scheduleCapableField;
    
    private bool queryParmsSupportedField;
    
    private bool queryParmsSupportedFieldSpecified;
    
    private bool receivesMetadataField;
    
    private bool receivesMetadataFieldSpecified;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("metaFormat", IsNullable=false)]
    public MetaFormat[] metaFormats {
        get {
            return this.metaFormatsField;
        }
        set {
            this.metaFormatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("metaSessionType", IsNullable=false)]
    public SessionType[] metaSessionTypes {
        get {
            return this.metaSessionTypesField;
        }
        set {
            this.metaSessionTypesField = value;
        }
    }
    
    /// <remarks/>
    public bool multicastCapable {
        get {
            return this.multicastCapableField;
        }
        set {
            this.multicastCapableField = value;
        }
    }
    
    /// <remarks/>
    public bool scheduleCapable {
        get {
            return this.scheduleCapableField;
        }
        set {
            this.scheduleCapableField = value;
        }
    }
    
    /// <remarks/>
    public bool queryParmsSupported {
        get {
            return this.queryParmsSupportedField;
        }
        set {
            this.queryParmsSupportedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool queryParmsSupportedSpecified {
        get {
            return this.queryParmsSupportedFieldSpecified;
        }
        set {
            this.queryParmsSupportedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool receivesMetadata {
        get {
            return this.receivesMetadataField;
        }
        set {
            this.receivesMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool receivesMetadataSpecified {
        get {
            return this.receivesMetadataFieldSpecified;
        }
        set {
            this.receivesMetadataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:psialliance-org")]
public enum MetaFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("gmch-psia")]
    gmchpsia,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("xml-psia")]
    xmlpsia,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:psialliance-org")]
public partial class SessionType {
    
    private SessionProtocolType metaSessionProtocolField;
    
    private SessionFlowType metaSessionFlowTypeField;
    
    private bool metaSessionFlowTypeFieldSpecified;
    
    private bool metaSessionPersistentField;
    
    private bool metaSessionPersistentFieldSpecified;
    
    /// <remarks/>
    public SessionProtocolType metaSessionProtocol {
        get {
            return this.metaSessionProtocolField;
        }
        set {
            this.metaSessionProtocolField = value;
        }
    }
    
    /// <remarks/>
    public SessionFlowType metaSessionFlowType {
        get {
            return this.metaSessionFlowTypeField;
        }
        set {
            this.metaSessionFlowTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool metaSessionFlowTypeSpecified {
        get {
            return this.metaSessionFlowTypeFieldSpecified;
        }
        set {
            this.metaSessionFlowTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool metaSessionPersistent {
        get {
            return this.metaSessionPersistentField;
        }
        set {
            this.metaSessionPersistentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool metaSessionPersistentSpecified {
        get {
            return this.metaSessionPersistentFieldSpecified;
        }
        set {
            this.metaSessionPersistentFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:psialliance-org")]
public enum SessionProtocolType {
    
    /// <remarks/>
    RESTSyncSessionTargetSend,
    
    /// <remarks/>
    RESTAsyncSessionBackSourceSend,
    
    /// <remarks/>
    RESTRTPStreamSrcOutUDP,
    
    /// <remarks/>
    RESTRTPStreamSrcOutTCP,
    
    /// <remarks/>
    RTSPRTPStreamSrcOut,
    
    /// <remarks/>
    RTSPRTPStreamSrcOutInterleaved,
    
    /// <remarks/>
    RESTAsyncSessionBackForReceive,
    
    /// <remarks/>
    RESTRTPStreamInUDP,
    
    /// <remarks/>
    RESTRTPStreamInTCP,
    
    /// <remarks/>
    EmailNotification,
    
    /// <remarks/>
    RESTSessionSrcOutRawTCP,
    
    /// <remarks/>
    RESTSessionIntoSrcRawTCP,
    
    /// <remarks/>
    RESTStreamSrcOutRawUDP,
    
    /// <remarks/>
    RESTRTPAsyncStreamSrcOutUDP,
    
    /// <remarks/>
    RESTAsyncSessionSrcOutRawTCP,
    
    /// <remarks/>
    RESTAsyncSessionSrcOutRawUDP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:psialliance-org")]
public enum SessionFlowType {
    
    /// <remarks/>
    datastream,
    
    /// <remarks/>
    transaction,
    
    /// <remarks/>
    streamOrTransaction,
    
    /// <remarks/>
    stateful,
    
    /// <remarks/>
    streamAndOrStateful,
}
