//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PSIA.Common.Soap.Objects
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class PsiaProfile
    {

        private string systemIDField;

        private string nativeIDField;

        private float psiaServiceVersionField;

        private PsiaSpecDecl primaryPsiaSpecField;

        private PsiaSpecDecl[] otherSpecListField;

        private PsiaProfileDecl[] profileListField;

        private string nodeDescriptionField;

        private string versionField;

        /// <remarks/>
        public string systemID
        {
            get
            {
                return this.systemIDField;
            }
            set
            {
                this.systemIDField = value;
            }
        }

        /// <remarks/>
        public string nativeID
        {
            get
            {
                return this.nativeIDField;
            }
            set
            {
                this.nativeIDField = value;
            }
        }

        /// <remarks/>
        public float psiaServiceVersion
        {
            get
            {
                return this.psiaServiceVersionField;
            }
            set
            {
                this.psiaServiceVersionField = value;
            }
        }

        /// <remarks/>
        public PsiaSpecDecl primaryPsiaSpec
        {
            get
            {
                return this.primaryPsiaSpecField;
            }
            set
            {
                this.primaryPsiaSpecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("psiaSpecDefn", IsNullable = false)]
        public PsiaSpecDecl[] otherSpecList
        {
            get
            {
                return this.otherSpecListField;
            }
            set
            {
                this.otherSpecListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("psiaProfileDefn", IsNullable = false)]
        public PsiaProfileDecl[] profileList
        {
            get
            {
                return this.profileListField;
            }
            set
            {
                this.profileListField = value;
            }
        }

        /// <remarks/>
        public string nodeDescription
        {
            get
            {
                return this.nodeDescriptionField;
            }
            set
            {
                this.nodeDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class PsiaSpecDecl
    {

        private PsiaSpecTag psiaSpecNameField;

        private float psiaSpecVersionField;

        private PsiaSpecProfileLevel psiaSpecProfileField;

        private bool psiaSpecProfileFieldSpecified;

        private string psiaSpecInfoField;

        /// <remarks/>
        public PsiaSpecTag psiaSpecName
        {
            get
            {
                return this.psiaSpecNameField;
            }
            set
            {
                this.psiaSpecNameField = value;
            }
        }

        /// <remarks/>
        public float psiaSpecVersion
        {
            get
            {
                return this.psiaSpecVersionField;
            }
            set
            {
                this.psiaSpecVersionField = value;
            }
        }

        /// <remarks/>
        public PsiaSpecProfileLevel psiaSpecProfile
        {
            get
            {
                return this.psiaSpecProfileField;
            }
            set
            {
                this.psiaSpecProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool psiaSpecProfileSpecified
        {
            get
            {
                return this.psiaSpecProfileFieldSpecified;
            }
            set
            {
                this.psiaSpecProfileFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string psiaSpecInfo
        {
            get
            {
                return this.psiaSpecInfoField;
            }
            set
            {
                this.psiaSpecInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum PsiaSpecTag
    {

        /// <remarks/>
        ipmd,

        /// <remarks/>
        racm,

        /// <remarks/>
        videoAnalytics,

        /// <remarks/>
        cmem,

        /// <remarks/>
        areaCtl,

        /// <remarks/>
        csec,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("other-PSIA")]
        otherPSIA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("other-private")]
        otherprivate,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum PsiaSpecProfileLevel
    {

        /// <remarks/>
        core,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("core+")]
        core1,

        /// <remarks/>
        basic,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("basic+")]
        basic1,

        /// <remarks/>
        extnded,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("extended+")]
        extended,

        /// <remarks/>
        full,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("full+")]
        full1,

        /// <remarks/>
        advanced,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("advanced+")]
        advanced1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public partial class PsiaProfileDecl
    {

        private string psiaProfileNameField;

        private float psiaProfileVersionField;

        private PsiaSpecTag psiaSpecField;

        /// <remarks/>
        public string psiaProfileName
        {
            get
            {
                return this.psiaProfileNameField;
            }
            set
            {
                this.psiaProfileNameField = value;
            }
        }

        /// <remarks/>
        public float psiaProfileVersion
        {
            get
            {
                return this.psiaProfileVersionField;
            }
            set
            {
                this.psiaProfileVersionField = value;
            }
        }

        /// <remarks/>
        public PsiaSpecTag psiaSpec
        {
            get
            {
                return this.psiaSpecField;
            }
            set
            {
                this.psiaSpecField = value;
            }
        }
    }
}