//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PSIA.Common.Soap.Objects.Model
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class QueryStringParameter
    {

        private string nameField;

        private string typeField;

        private string descriptionField;

        private QueryStringParameterExt extensionsField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public QueryStringParameterExt Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class QueryStringParameterExt
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class QueryStringParameterList
    {

        private QueryStringParameter[] queryStringParameterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueryStringParameter")]
        public QueryStringParameter[] QueryStringParameter
        {
            get
            {
                return this.queryStringParameterField;
            }
            set
            {
                this.queryStringParameterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class URLParameters
    {

        private QueryStringParameter[] queryStringParameterListField;

        private string inboundDataField;

        private string returnResultField;

        private string functionField;

        private string notesField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public QueryStringParameter[] QueryStringParameterList
        {
            get
            {
                return this.queryStringParameterListField;
            }
            set
            {
                this.queryStringParameterListField = value;
            }
        }

        /// <remarks/>
        public string inboundData
        {
            get
            {
                return this.inboundDataField;
            }
            set
            {
                this.inboundDataField = value;
            }
        }

        /// <remarks/>
        public string returnResult
        {
            get
            {
                return this.returnResultField;
            }
            set
            {
                this.returnResultField = value;
            }
        }

        /// <remarks/>
        public string function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }

        /// <remarks/>
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class ResponseStatus
    {

        private string requestURLField;

        private int statusCodeField;

        private string statusStringField;

        private string idField;

        private ResponseStatusExt extensionsField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string requestURL
        {
            get
            {
                return this.requestURLField;
            }
            set
            {
                this.requestURLField = value;
            }
        }

        /// <remarks/>
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        public string statusString
        {
            get
            {
                return this.statusStringField;
            }
            set
            {
                this.statusStringField = value;
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public ResponseStatusExt Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class ResponseStatusExt
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class ResourceDescription
    {

        private string nameField;

        private string versionField;

        private ResourceType typeField;

        private string descriptionField;

        private string notesField;

        private URLParameters getField;

        private URLParameters putField;

        private URLParameters postField;

        private URLParameters deleteField;

        private System.Xml.XmlElement[] anyField;

        private string version1Field;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public ResourceType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        public URLParameters get
        {
            get
            {
                return this.getField;
            }
            set
            {
                this.getField = value;
            }
        }

        /// <remarks/>
        public URLParameters put
        {
            get
            {
                return this.putField;
            }
            set
            {
                this.putField = value;
            }
        }

        /// <remarks/>
        public URLParameters post
        {
            get
            {
                return this.postField;
            }
            set
            {
                this.postField = value;
            }
        }

        /// <remarks/>
        public URLParameters delete
        {
            get
            {
                return this.deleteField;
            }
            set
            {
                this.deleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string version1
        {
            get
            {
                return this.version1Field;
            }
            set
            {
                this.version1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    public enum ResourceType
    {

        /// <remarks/>
        service,

        /// <remarks/>
        resource,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class Resource
    {

        private string nameField;

        private string versionField;

        private ResourceType typeField;

        private string descriptionField;

        private ResourceList resourceListField;

        private ResourceExt extensionsField;

        private string version1Field;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public ResourceType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public ResourceList ResourceList
        {
            get
            {
                return this.resourceListField;
            }
            set
            {
                this.resourceListField = value;
            }
        }

        /// <remarks/>
        public ResourceExt Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string version1
        {
            get
            {
                return this.version1Field;
            }
            set
            {
                this.version1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class ResourceList
    {

        private Resource[] resourceField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Resource")]
        public Resource[] Resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:psialliance-org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:psialliance-org", IsNullable = false)]
    public partial class ResourceExt
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
}